FROM node:24-trixie-slim AS build
WORKDIR /pcap
RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  g++ \
  libpcap-dev \
  make \
  python3
COPY . .
RUN npm ci --ignore-scripts
RUN MAKEFLAGS=-j$(nproc) npx -y @audc/prebuild

FROM scratch
COPY --from=build /pcap/prebuilds .
