name: Add native binaries to release

on:
  push:
    tags: ['*']
  workflow_dispatch:

jobs:
  prebuild:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v4
      - name: Use nodejs
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install dependencies on Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libpcap-dev
        shell: bash
      - name: Install dependencies on macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install libpcap
        shell: bash
      - name: Dependencies
        run: |
          npm install --ignore-scripts
      - name: Build
        run: |
          npx prebuild --target 18.0.0
          npx prebuild --target 20.0.0
          npx prebuild --target 22.0.0
      - name: Upload
        run: |
          npx prebuild --upload-all ${{ secrets.UPLOAD_TOKEN }}
        env:
          MAKEFLAGS: -j4

  prebuild-alpine:
    name: alpine
    runs-on: ubuntu-latest
    container: node:alpine
    steps:
      - uses: actions/checkout@v4
      - name: Use nodejs
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install build deps
        run: |
          apk add g++ libpcap-dev make python3
      - name: Dependencies
        run: |
          npm install --ignore-scripts
      - name: Build
        run: |
          npx prebuild --target 18.0.0
          npx prebuild --target 20.0.0
          npx prebuild --target 22.0.0
      - name: Upload
        run: |
          npx prebuild --upload-all ${{ secrets.UPLOAD_TOKEN }}
        env:
          MAKEFLAGS: -j4
